### ISSUE TITLE
Custom Variables

### ISSUE THREAD

**Issue by smurfiez** [half2me/curlx#6]
How do you pass in custom variables , in the original
function callback_functn($response, $url, $request_info, $user_data, $time) {
    $time; //how long the request took in milliseconds (float)
    $request_info; //returned by curl_getinfo($ch)
}

It was user_data, what is it now?

**Comment by half2me** [comment]
For example usage please see the Readme file, this works differently from CURL.
For production use though, I would recommend not using my library, but using https://github.com/guzzle/guzzle instead. When I made this library, I was unaware of Guzzle's existence. It is far more superior than my lib, so use that :)
