### ISSUE TITLE
Add an example/explanation  for the agent's default options

### ISSUE THREAD

**Issue by tsirolnik** [half2me/curlx#7]
It is not clear whether something like this would work or not - 
```php
    $agent->options = ['CURLOPT_SOME_OPTION' => 'your-value'];
```
And would cause the new requests to use this option or not.

Please consider adding an example/explanation to make it clearer.

Thanks

**Comment by half2me** [comment]
@tsirolnik this project is abandoned. use [Guzzle](https://github.com/guzzle/guzzle)
